<p>
    <h2>Name:Prabhu Dahal</h2>
    <h2>Roll No: 57</h2>
    <h2>Group: Computer Science</h2>
</p>

### Imports

In [2]:
# !pip install gym 

In [34]:
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd
import sys
import os

## Chapter 15 – Artificial Intelligence with Python

In [33]:
import argparse
import gym

In [5]:
# def build_arg_parser():
#     parser = argparse.ArgumentParser(description='Run an environment')
#     parser.add_argument('--input-env', dest='input_env', required=True,
#             help='Specify the name of the environment')
#     return parser

### Creating the environment

In [34]:
def environment_main(input_env):
    input_env = input_env
    name_map = {'cartpole': 'CartPole-v0', 
                'mountaincar': 'MountainCar-v0',
                'pendulum': 'Pendulum-v0',
                'taxi': 'Taxi-v1',
                'lake': 'FrozenLake-v0'}

    # Create the environment and reset it
    env = gym.make(name_map[input_env])
    env.reset()

    # Iterate 1000 times
    for _ in range(1000):
        # Render the environment
        env.render()

        # take a random action
        env.step(env.action_space.sample())    
    env.close()

In [33]:
environment_main('cartpole')

In [32]:
environment_main('mountaincar')

### Building a learning agent

In [35]:
# if __name__=='__main__':
choices=['cartpole', 'mountaincar', 'pendulum', 'taxi', 'lake'], 

def balancer_main(input_env):
#     args = build_arg_parser().parse_args()
    input_env = input_env

    name_map = {'cartpole': 'CartPole-v0', 
                'mountaincar': 'MountainCar-v0',
                'pendulum': 'Pendulum-v0'}

    # Create the environment 
    env = gym.make(name_map[input_env])

    # Start iterating 
    for _ in range(20):
        # Reset the environment
        observation = env.reset()

        # Iterate 100 times
        for i in range(100):
            # Render the environment
            env.render()

            # Print the current observation
            print(observation)

            # Take action 
            action = env.action_space.sample()

            # Extract the observation, reward, status and 
            # other info based on the action taken
            observation, reward, done, info = env.step(action)
            
            # Check if it's done
            if done:
                print('Episode finished after {} timesteps'.format(i+1))
                break
    env.close()

In [36]:
balancer_main('cartpole')

[ 0.00297555 -0.02974582  0.00830616  0.04238035]
[ 0.00238063  0.16525604  0.00915377 -0.24767037]
[ 0.00568575  0.36024608  0.00420036 -0.537452  ]
[ 0.01289068  0.55530872 -0.00654868 -0.82880848]
[ 0.02399685  0.36027691 -0.02312485 -0.53819233]
[ 0.03120239  0.5557162  -0.03388869 -0.83807099]
[ 0.04231671  0.75128415 -0.05065011 -1.14121585]
[ 0.0573424   0.94703022 -0.07347443 -1.44934316]
[ 0.076283    0.75288432 -0.10246129 -1.18049209]
[ 0.09134069  0.55923073 -0.12607113 -0.92160609]
[ 0.1025253   0.75581003 -0.14450326 -1.25110163]
[ 0.1176415   0.56280468 -0.16952529 -1.00694725]
[ 0.12889759  0.7597345  -0.18966423 -1.34770954]
Episode finished after 13 timesteps
[-0.00282439  0.00426088  0.02334313 -0.02769773]
[-0.00273918  0.19904043  0.02278917 -0.3129252 ]
[ 0.00124163  0.00360136  0.01653067 -0.01314329]
[ 0.00131366 -0.19175371  0.01626781  0.28470908]
[-0.00252141  0.00313249  0.02196199 -0.00279902]
[-0.00245876  0.1979327   0.02190601 -0.28847257]
[0.00149989 0.

##  Mastering Machine Learning with Python in Six Steps

<center><h2>Chapter 6- Deep and Reinforcement Learning</h2></center>

<h2>Reinforcement Learning</h2>

Reinforcement learning is a goal-oriented learning method based on interaction with
its environment. The objective is getting an agent to act in an environment in order to
maximize its rewards. Here the agent is an intelligent program, and environment is the
external condition

Let’s consider an example of a predefined system for teaching a new trick to a dog,
where you do not have to tell the dog what to do. However, you can reward the dog, if it
does it right or punish if it does wrong. With every step, it has to remember what made it
get the reward or punishment; this is commonly known as a credit assignment problem.
Similarly, we can train a computer agent such that its objective is to take action to move
from state st to state st+1 and find behavior function to maximize the expected sum of
discounted rewards and map the states to actions. According to the paper published
by Deepmind Technologies in 2013, the Q-learning rule for updating status is given by:

Q[s,z]<sub>new</sub> = Q[s,a]<sub>prev</sub> + α * (r+y*max(s,a)-Q[s,a]<sub>prev</sub>) where
<ul>
    <li>α is the learning rate</li>
    <li> r is reward for latest action,</li>
    <li>y is the discounted factor, and</li>
    <li>max(s,a) is the estimate of new value from best action.</li>
</ul>

In [35]:
from random import randint

In [36]:
# defines the reward/link connection graph
R = np.matrix([[-1, -1, -1, -1,  0,  -1],
              [-1, -1, -1,  0, -1, 100],
              [-1, -1, -1,  0, -1,  -1],
              [-1,  0,  0, -1,  0,  -1],
              [ 0, -1, -1,  0, -1, 100],
              [-1,  0, -1, -1,  0, 100]])
Q = np.zeros_like(R)

In [37]:
# learning parameter
gamma = 0.8

# Initialize random_state
initial_state = randint(0,4)

In [38]:
# This function returns all available actions in the state given as an argument
def available_actions(state):
    current_state_row = R[state,]
    av_act = np.where(current_state_row >= 0)[1]
    return av_act

# This function chooses at random which action to be performed within the range 
# of all the available actions.
def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_act,1))
    return next_action

# This function updates the Q matrix according to the path selected and the Q 
# learning algorithm
def update(current_state, action, gamma):
    
    max_index = np.where(Q[action,] == np.max(Q[action,]))[1]

    if max_index.shape[0] > 1:
        max_index = int(np.random.choice(max_index, size = 1))
    else:
        max_index = int(max_index)
    max_value = Q[action, max_index]
    
    # Q learning formula
    Q[current_state, action] = R[current_state, action] + gamma * max_value    

In [39]:
# Get available actions in the current state
available_act = available_actions(initial_state) 

# Sample next action to be performed
action = sample_next_action(available_act)

In [40]:
# Train over 100 iterations, re-iterate the process above).
for i in range(100):
    current_state = np.random.randint(0, int(Q.shape[0]))
    available_act = available_actions(current_state)
    action = sample_next_action(available_act)
    update(current_state,action,gamma)
    
# Normalize the "trained" Q matrix
print("Trained Q matrix: \n", Q/np.max(Q)*100)

Trained Q matrix: 
 [[  0.           0.           0.           0.          76.19047619
    0.        ]
 [  0.           0.           0.          60.95238095   0.
   95.23809524]
 [  0.           0.           0.          60.95238095   0.
    0.        ]
 [  0.          76.19047619  45.71428571   0.          76.19047619
    0.        ]
 [ 35.           0.           0.          60.95238095   0.
   95.23809524]
 [  0.          71.42857143   0.           0.          76.19047619
  100.        ]]


In [41]:
current_state = 2
steps = [current_state]

while current_state != 5:
    next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[1]
    if next_step_index.shape[0] > 1:
        next_step_index = int(np.random.choice(next_step_index, size = 1))
    else:
        next_step_index = int(next_step_index)
    steps.append(next_step_index)
    current_state = next_step_index

# Print selected sequence of steps
print("Best sequence path: ", steps)

Best sequence path:  [2, 3, 1, 5]
